### ISSUE TITLE
Releasing the plugin?

### ISSUE THREAD

**Issue by cplim** [oyvinmar/grails-closure-compiler#1]
Hi,

I was wondering if it is possible for you to release this plugin?  Or if it is already released, what is the link to it on the grails website?

regards,
CP

**Comment by oyvinmar** [comment]
It's not really ready yet. I would like to add support for simple and advanced compilation parameters. I also need to test the handling of errors and warnings from the closure compiler a bit first.

I'm quite busy with other projects at work, but I'll try to get it ready as soon as possible.

**Comment by cplim** [comment]
Ok, no problem.  If there are a list of things that you'd like to do, I'd be happy to help.  Perhaps you can raise them as issues on this project and I can submit pull requests if I manage to fix them?

**Comment by oyvinmar** [comment]
The plugin is now released (see: http://grails.org/plugin/closure-compiler ). Please let me know if you have any issues with it!

**Comment by cplim** [comment]
Cool!  Thanks.  Will look forward to using it in our project!
