### ISSUE TITLE
multiple js files obfuscation

### ISSUE THREAD

**Issue by mcheung63** [oyvinmar/grails-closure-compiler#13]
Hi, if i have many js files, they all using variables in other js, is it a problem? Because this plugin only obfuscate 1 file at 1 time.

**Comment by oyvinmar** [comment]
I think that would be a problem. This plugin depends on the resources plugin where the compression phase is before the aggregation phase (see: http://grails-plugins.github.io/grails-resources/guide/6.%20Creating%20custom%20mappers.html#6.2%20Mapper%20phases%20and%20priority).
 
This should not be an issue if you set compilation level to WHITESPACE_ONLY
