### ISSUE TITLE
plugin scope

### ISSUE THREAD

**Issue by ghost** [oyvinmar/grails-closure-compiler#5]
According to the docs, this plugin should installed by adding the following to `BuildConfig.groovy`

```
compile ":closure-compiler:0.9.1"
```

But does this plugin really need to have a compile scope? I'd have thought that build or runtime should be sufficient.

**Comment by oyvinmar** [comment]
As far as I know it should work with runtime scope. The doc on grails.org is generated from an plugin descriptor. I don't know where I can specify the scope (maybe it defaults to compile).
