### ISSUE TITLE
excludes .min.js rule not work with cached-resources plugin.

### ISSUE THREAD

**Issue by lyhcode** [oyvinmar/grails-closure-compiler#6]
Hi,

If closure-compiler plugin work with cached-resources plugin,
It seems process original name '.min.js' files.
Not apply to excludes rules.
I think the problem is cached-resources plugin translate all js file name to .js suffix.
So the .min.js suffix excludes rules not work.

**Comment by oyvinmar** [comment]
That shouldn't be a problem. ClosureCompiler uses the COMPRESSION mapperphase which happens before cached-resources RENAMING phase (see: https://github.com/grails-plugins/grails-resources/blob/master/src/groovy/org/grails/plugin/resource/mapper/MapperPhase.groovy).

I use both plugins in a project without issues.
