### ISSUE TITLE
compression takes place before aggregation

### ISSUE THREAD

**Issue by thetrav** [oyvinmar/grails-closure-compiler#8]
My understanding is that compression on aggregated js files would be more effective than aggregation on small individual js files.

Additionally when the closure-compiler is configured for ECM5SCRIPT_STRICT it inserts "use strict"; at the beginning of each file.

This directive is ignored if it is not the first line of a file, so you've got a lot of extra bytes for no benefit.

**Comment by oyvinmar** [comment]
The phase priority is controlled by the Grails Resource Plugin.
